# Generated by Django 3.2.12 on 2022-03-22 19:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
